--- mini_httpd-1.30/Makefile	2017-02-28 15:10:51.000000000 +0100
+++ mini_httpd-1.30-patch/Makefile	2019-12-29 19:44:50.262073173 +0100
@@ -22,19 +22,19 @@
 
 BINDIR =	/usr/local/sbin
 MANDIR =	/usr/local/man
-CC =		cc
+CC =		afl-clang-fast
 CDEFS =		$(SSL_DEFS) $(SSL_INC)
-CFLAGS =	-O $(CDEFS) -ansi -pedantic -U__STRICT_ANSI__ -Wall -Wpointer-arith -Wshadow -Wcast-qual -Wcast-align -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wno-long-long
-LDFLAGS =	-s
+CFLAGS =	-O -ggdb -DHAVE_INT64T $(CDEFS) -ansi -pedantic -U__STRICT_ANSI__ -Wall -Wpointer-arith -Wshadow -Wcast-qual -Wcast-align -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wno-long-long
+LDFLAGS =	
 LDLIBS =	$(CRYPT_LIB) $(SSL_LIBS) $(SYSV_LIBS)
 
 all:		mini_httpd htpasswd
 
 mini_httpd:	mini_httpd.o match.o tdate_parse.o
-	$(CC) $(LDFLAGS) mini_httpd.o match.o tdate_parse.o $(LDLIBS) -o mini_httpd
+	#$(CC) $(LDFLAGS) mini_httpd.o match.o tdate_parse.o $(LDLIBS) -o mini_httpd
 
 mini_httpd.o:	mini_httpd.c version.h port.h match.h tdate_parse.h mime_encodings.h mime_types.h
-	$(CC) $(CFLAGS) -c mini_httpd.c
+	$(CC) -c mini_httpd.c
 
 match.o:	match.c match.h
 	$(CC) $(CFLAGS) -c match.c
